Решение задач 5, 6 модуля
js-tasks-ru/js-20201030_twangste pull request #5
Opened 2020-11-19 20:14 UTC by twangest

2020-11-19 22:04 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +const notifications = [];
эту переменную нужно убрать, она не используется

2020-11-19 22:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  timer = null;
от поля `timer` можно избавиться

2020-11-19 22:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.timer = setTimeout(() => {
можно не присваивать `id` таймера в `this.timer`

2020-11-19 22:07 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    const sortOrder = {
good 👍

2020-11-19 22:09 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.sort(initialSortedFieldName, 'asc');
а почему бы нам сразу не отсортировать данные в нужном порядке перед первым рендером? У нас есть все возможности для этого. Попробуйте это исправить

2020-11-19 22:09 UTC, dosandk requested changes
нужно поправить решение SortableTable, посмотрите пожалуйста коммент

2020-11-20 00:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
Tooltip компонент
- should be rendered correctly
- should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-11-20 02:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
Tooltip компонент
- should be rendered correctly
- should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-11-20 03:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
Tooltip компонент
- should be rendered correctly
- should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-11-20 13:35 UTC, dosandk approved these changes

2020-11-20 13:35 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-20 15:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-21 21:19 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  moveTooltip = (el) => {
старайтесь предерживаться одного стиля именования. Если вы используете имя аргумента `element` для методов `showTooltip` и `closeTooltip` то неплохо было бы дать такое же имя и для аргумента `moveTooltip`

2020-11-21 21:25 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      elem.addEventListener('pointermove', this.moveTooltip);
помните мы на занятии разбирали прем "делегирование событий" (event-delegation). 
Определенно нужно заменить добавление обработчиков через `forEach` на добавление всего 2х обработчиков на `document`. 
Основной аргумент - производительность. Меньшее количество обработчиков в документе всегда лучше влияет на производительность.
Второй аргумент - тултип не будет работать для вновь добавленных элементы на страницу, без перезапуска этого метода. Вспомните пример с фруктами, который мы разбирали на занятии.

2020-11-21 21:25 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        elem.removeEventListener('pointermove', this.moveTooltip);
попробуйте избавиться от обработчика `pointermove `, посмотрите разбор ДЗ на занятии

2020-11-21 21:25 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-23 15:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-24 01:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-24 07:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-24 08:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-24 08:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-24 10:46 UTC, dosandk approved these changes
good 👍

2020-11-24 10:47 UTC, merged